import { IApp, GetAppConfig, IQlik, IUser, ListTypes } from "./types";
export default class Qlik {
    config: GetAppConfig;
    qlik: IQlik;
    baseUrl: string;
    saasURL: string;
    user: IUser;
    docList: IApp[];
    currApps: any[];
    ticket?: string;
    isSaaS: boolean;
    webIntegrationId: string;
    constructor(config: GetAppConfig);
    private appendScript;
    private appendStylesheet;
    callRequire(): Promise<void>;
    setQlik(): Promise<IQlik>;
    private fetchAPI;
    authenticateToQlik(): Promise<void>;
    setAuthUser(): Promise<void>;
    getMoreData(response: any, data?: any[]): Promise<any>;
    getSpace(id: string): Promise<any>;
    getSpaceList(): Promise<any[]>;
    getUserList(): Promise<any[]>;
    getAppList(): Promise<any[]>;
    getThemeList(): Promise<any[]>;
    getDocs(): Promise<IApp[]>;
    getList(app: IApp, type: ListTypes): Promise<any>;
    getMeasure(app: IApp): Promise<any>;
    getVariable(app: IApp): Promise<any>;
    getFields(app: IApp): Promise<any>;
    getBookmark(app: IApp): Promise<any>;
    evaluateExpression(app: IApp, title: any): Promise<any>;
    objectProper(app: IApp, model: any): Promise<any>;
    getQlikObjectTitles(app: IApp, id: string): Promise<any>;
    getSheet(app: IApp): Promise<any>;
    callObject(app: IApp, id: string): Promise<any>;
    checkAppOpen(app: IApp): Promise<IApp>;
    isAppOpen(id: string): Promise<IApp>;
    getApp(id: string): Promise<any[]>;
}
